resources:
- gitops-deployment.yaml
- gitops-service.yaml
- gitops-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 192.168.31.109/gitops-project/gitops-project
  newTag: 6ae208af
